language: java

jdk:
  - openjdk8

cache:
  directories:
  - .buildtools
  - $HOME/.m2

before_install:
  - chmod +x scripts/buildtools.sh
  - scripts/buildtools.sh

script:
  - echo "skipping tests"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file:
    - "/home/travis/.m2/repository/net/ess3/EssentialsX/2.17.1/EssentialsX-2.17.1.jar"
  on:
    tags: true
    branch: 2.x
