language: java

jdk:
  - openjdk8

cache:
  directories:
  - .buildtools
  - $HOME/.m2

before_install:
  - chmod +x scripts/buildtools.sh
  - scripts/buildtools.sh

script:
  - echo "skipping tests"

deploy:
  provider: releases
#  edge: true
  api_key: $GH_TOKEN
  skip_cleanup: true
  file:
    - EssentialsX/Essentials/target/EssentialsX-2.17.1.1.jar
  draft: true
  on:
    tags: false
    branch: 2.x
