language: java

jdk:
  - openjdk8

cache:
  directories:
  - .buildtools
  - $HOME/.m2

before_install:
  - chmod +x scripts/buildtools.sh
  - scripts/buildtools.sh

script:
  - echo "skipping tests"

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
