language: java

jdk:
  - openjdk8

cache:
  directories:
  - .buildtools
  - $HOME/.m2

before_install:
  - chmod +x scripts/buildtools.sh
  - scripts/buildtools.sh

script:
  - echo "skipping tests"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - EssentialsX-2.17.1.jar
  skip_cleanup: true
  on:
    tags: false
