# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
softdepend: [Vault]
authors: [almic, Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685]
api-version: 1.15
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [player/message...]
  antioch:
    description: 'A little surprise for operators.'
    usage: /<command> [message]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command> [player]
  backup:
    description: Runs the backup if configured.
    usage: /<command>
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: bal
  balancetop:
    description: Gets the top balance values.
    usage: /<command> <page>
    aliases: baltop
  ban:
    description: Bans a player.
    usage: /<command> <player> [reason]
  banip:
    description: Bans an IP address.
    usage: /<command> <address>
  beezooka:
    description: Throw an exploding bee at your opponent.
    usage: /<command>
  book:
    description: Allows reopening and editing of sealed books.
    usage: /<command> [title|author [name]]
  break:
    description: Breaks the block you are looking at.
    usage: /<command>
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> <msg>
  broadcastworld:
    description: Broadcasts a message to a world.
    usage: /<command> <world> <msg>
  bigtree:
    description: Spawn a big tree where you are looking.
    usage: /<command> <tree|redwood|jungle|darkoak>
  burn:
    description: Set a player on fire.
    usage: /<command> <player> <seconds>
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command> [player|*] [item[:<data>]|*|**] [amount]
  clearinventoryconfirmtoggle:
    description: Toggles whether you are prompted to confirm inventory clears.
    usage: /<command>
    aliases: [clearconfirmoff, clearconfirmon, clearconfirm]
  condense:
    description: Condenses items into a more compact blocks.
    usage: /<command> [<itemname>|<id>|hand|inventory]
    aliases: compact
  compass:
    description: Describes your current bearing.
    usage: /<command>
    aliases: direction
  createkit:
    description: Create a kit in game!
    usage: /<command> <kitname> <delay>
  customtext:
    description: Allows you to create custom text commands.
    usage: /<alias> - Define in bukkit.yml
  delhome:
    description: Removes a home.
    usage: /<command> [player:]<name>
  deljail:
    description: Removes a jail.
    usage: /<command> <jailname>
  delkit:
    description: Deletes the specified kit.
    usage: /<command> <kit>
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> <warp>
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
    aliases: height
  disposal:
    description: Opens a portable disposal menu.
    usage: /<command>
    aliases: trash
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: economy
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
  enderchest:
    description: Lets you see inside an enderchest.
    usage: /<command> [player]
    aliases: echest
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: ess
  exp:
    description: Give, set or look at a players exp.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: xp
  ext:
    description: Extinguish players.
    usage: /<command> [player]
    aliases: extinguish
  feed:
    description: Satisfy the hunger.
    usage: /<command> [player]
    aliases: eat
  fly:
    description: Take off, and soar!
    usage: /<command> [player] [on|off]
  fireball:
    description: Throw a fireball or other assorted projectiles.
    usage: /<command> [fireball|small|large|arrow|skull|egg|snowball|expbottle|dragon|splashpotion|lingeringpotion|trident] [speed]
    aliases: [efireball,fireentity,efireentity,fireskull,efireskull]
  firework:
    description: Allows you to modify a stack of fireworks.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
  gamemode:
    description: Change player gamemode.
    usage: /<command> <survival|creative|adventure|spectator> [player]
    aliases: [adventure, creative, survival, spectator, gm, gma, gmc, gms, gmt]
  gc:
    description: Reports memory, uptime and tick info.
    usage: /<command> [all]
    aliases: [lag, mem, memory, uptime, tps, entities]
  getpos:
    description: Get your current coordinates or those of a player.
    usage: /<command> [player]
    aliases: [coords, position]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount [itemmeta...]]
  god:
    description: Enables your godly powers.
    usage: /<command> [player] [on|off]
    aliases: godmode
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
  heal:
    description: Heals you or the given player.
    usage: /<command> [player]
  help:
    description: Views a list of available commands.
    usage: /<command> [search term] [page]
  home:
    description: Teleport to your home.
    usage: /<command> [player:][name]
    aliases: homes
  info:
    description: Shows information set by the server owner.
    usage: /<command> [chapter] [page]
    aliases: [about, news]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount [itemmeta...]]
    aliases: i
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
    aliases: [dura, durability, itemno]
  itemname:
    description: Names an item.
    usage: /<command> [name]
    aliases: [iname, itemrename, irename]
  jails:
    description: List all jails.
    usage: /<command>
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: jumpto
  kick:
    description: Kicks a specified player with a reason.
    usage: /<command> <player> [reason]
  kickall:
    description: Kicks all players off the server except the issuer.
    usage: /<command> [reason]
  kill:
    description: Kills specified player.
    usage: /<command> <player>
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> [kit] [player]
    aliases: kits
  kittycannon:
    description: Throw an exploding kitten at your opponent.
    usage: /<command>
  lightning:
    description: The power of Thor. Strike at cursor or player.
    usage: /<command> [player] [power]
    aliases: [smite, strike]
  more:
    description: Fills the item stack in hand to maximum size.
    usage: /<command>
  motd:
    description: Views the Message Of The Day.
    usage: /<command> [chapter] [page]
  nuke:
    description: May death rain upon them.
    usage: /<command> [player]
    aliases: [enuke]
  tpoffline:
    description: Teleport to a player's last known logout location
    usage: /<command> <player>
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
  paytoggle:
    description: Toggles whether you are accepting payments.
    usage: /<command>
    aliases: [payoff, payon]
  payconfirmtoggle:
    description: Toggles whether you are prompted to confirm payments.
    usage: /<command>
    aliases: [payconfirmoff, payconfirmon, payconfirm]
  ping:
    description: Pong!
    usage: /<command>
  potion:
    description: Adds custom potion effects to a potion.
    usage: /<command> <clear|apply|effect:<effect> power:<power> duration:<duration>>
  powertool:
    description: Assigns a command to the item in hand.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
  powertooltoggle:
    description: Enables or disables all current powertools.
    usage: /<command>
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: playertime
  pweather:
    description: Adjust a player's weather
    usage: /<command> [list|reset|storm|sun|clear] [player|*]
    aliases: playerweather
  recipe:
    description: Displays how to craft items.
    usage: /<command> <item> [number]
  remove:
    description: Removes entities in your world.
    usage: /<command> <all|tamed|named|drops|arrows|boats|minecarts|xp|paintings|itemframes|endercrystals|monsters|animals|ambient|mobs|[mobType]> [radius|world]
    aliases: [butcher, killall, mobkill]
  repair:
    description: Repairs the durability of one or all items.
    usage: /<command> [hand|all]
    aliases: fix
  rest:
    description: Rests you or the given player.
    usage: /<command> [player]
  rules:
    description: Views the server rules.
    usage: /<command> [chapter] [page]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
  sethome:
    description: Set your home to your current location.
    usage: /<command> [[player:]name]
    aliases: createhome
  setjail:
    description: Creates a jail where you specified named [jailname].
    usage: /<command> <jailname>
    aliases: createjail
  setwarp:
    description: Creates a new warp.
    usage: /<command> <warp>
    aliases: createwarp
  setworth:
    description: Set the sell value of an item.
    usage: /<command> [itemname|id] <price>
  showkit:
    description: Show contents of a kit.
    usage: /<command> <kitname>
    aliases: kitshow
  skull:
    description: Set the owner of a player skull
    usage: /<command> [owner]
    aliases: [playerskull, head]
  spawner:
    description: Change the mob type of a spawner.
    usage: /<command> <mob> [delay]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [player]
  speed:
    description: Change your speed limits.
    usage: /<command> [type] <speed> [player]
    aliases: [flyspeed, walkspeed]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
  suicide:
    description: Causes you to perish.
    usage: /<command>
  tempban:
    description: Temporary ban a user.
    usage: /<command> <playername> <datediff> <reason>
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
  time:
    description: Display/Change the world time. Defaults to current world.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day, night]
  togglejail:
    description: Jails/Unjails a player, TPs them to the jail specified.
    usage: /<command> <player> <jailname> [datediff]
    aliases: [jail, unjail]
  top:
    description: Teleport to the highest block at your current position.
    usage: /<command>
  tp:
    description: Teleport to a player.
    usage: /<command> <player> [otherplayer]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
    aliases: tpask
  tpaall:
    description: Requests all players online to teleport to you.
    usage: /<command> <player>
    aliases: tpaskall
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command> [otherplayer]
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> <player>
  tpauto:
    description: Automatically accept teleportation requests.
    usage: /<command> <player>
  tpacancel:
    description: Cancel all outstanding teleport requests. Specify [player] to cancel requests with them.
    usage: /<command> [player]
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player> [otherplayer]
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z> [yaw] [pitch] [world]
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command> [player] [on|off]
  tree:
    description: Spawn a tree where you are looking.
    usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
  unban:
    description: Unbans the specified player.
    usage: /<command> <player>
  unbanip:
    description: Unbans the specified IP address.
    usage: /<command> <address>
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> <list|item|clear> [player]
  vanish:
    description: Hide yourself from other players.
    usage: /<command> [player] [on|off]
    aliases: v
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> <pagenumber|warp> [player]
    aliases: warps
  weather:
    description: Sets the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain, storm, sun]
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [craft, wbench]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
    aliases: price

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  essentials.sleepingignored:
    default: false
    description: If the player has this permission, they will not have to sleep for the night to be skipped
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
  essentials.seen.extra:
    default: op
    children:
      essentials.seen.ip: true
      essentials.seen.location: true
  essentials.keepinv:
    default: false
    description: Controls whether players keep their inventory on death.
  essentials.keepxp:
    default: false
    description: Allows the user to keep their exp on death, instead of dropping it.
  essentials.invsee.preventmodify:
    default: false
    description: Prevents other players from modifying the players inventory.
  essentials.afk.auto:
    default: false
    description: Players with this permission will be set to afk after a period of inaction as defined in the config file.
  essentials.home.compass:
    default: false
    description: Point the player's compass at their first home. compass-towards-home-perm needs to be enabled in the configuration.
  essentials.ban.exempt:
    default: false
    description: Prevent a specified group or player from being banned
  essentials.kick.exempt:
    default: false
    description: Prevents the player from being kicked.
  essentials.kit.exemptdelay:
    default: false
    description: Exempts you from the kit delay feature, this affects signs as well as command.
  essentials.sethome.bed:
    default: false
    description: Allows the player to right click a bed during daytime to update their 'bed' home.
  essentials.silentjoin:
    default: false
    description: Allow to join silently
  essentials.silentjoin.vanish:
    default: false
    description: Allow to join silently, and get put in vanish mode
  essentials.silentquit:
    default: false
    description: Suppress leave/quit messages for users with this permission.
  essentials.sleepingignored:
    default: false
    description: User isn't required to be sleeping, for time to be reset.
  essentials.sudo.exempt:
    default: false
    description: Prevents the holder from being sudo'ed by another user
  essentials.tempban.exempt:
    default: false
    description: Prevents a specified group or player from being tempbanned
  essentials.balancetop.exclude:
    default: false
    description: Players with this permission are excluded from the balancetop
  essentials.back.onteleport:
    default: true
    description: Players with this permission will have back location stored during any teleportation
  essentials.back.ondeath:
    default: false
    description: Players with this permission will have back location stored during death
  essentials.exempt:
    default: false
    description: Parent permission to be exempt from many moderator actions
    children:
      essentials.invsee.preventmodify: true
      essentials.ban.exempt: true
      essentials.kick.exempt: true
      essentials.sudo.exempt: true
      essentials.tempban.exempt: true
      essentials.exempt.protect: true
